routes/web.php
<?php

use App\Http\Controllers\Admin\AdminController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Auth\AuthenticationController;
use App\Http\Controllers\User\UserController;
use Illuminate\Support\Facades\App;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\URL;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [AuthenticationController::class, 'login'])->name('login');

Route::post('login', [AuthenticationController::class, 'postLogin'])->name('submit-login');

Route::group(['as' => 'admin.', 'namespace' => 'admin', 'middleware' => 'auth_admin', 'prefix' => 'admin'], function () {

    Route::get('dashboard', [AdminController::class, 'adminDashboard'])->name('dashboard');

    Route::get('users-list', [AdminController::class, 'index'])->name('users-list');

    Route::get('create-user', [AdminController::class, 'getNewUserForm'])->name('create-user');
    Route::post('store-user', [AdminController::class, 'storeUserDetails'])->name('store-user');

    Route::get('edit-user/{id}', [AdminController::class, 'getUpdateUserForm'])->name('edit-user');
    Route::post('update-user', [AdminController::class, 'updateUserDetails'])->name('update-user');

    Route::get('delete-user/{id?}', [AdminController::class, 'deleteUser'])->name('delete-user');

    Route::any('logout', [AdminController::class, 'adminLogout'])->name('logout');
});


Route::group(['as' => 'user.', 'namespace' => 'user', 'middleware' => 'auth_user', 'prefix' => 'user'], function () {

    Route::get('dashboard', [UserController::class, 'userDashboard'])->name('dashboard');

    Route::any('logout', [UserController::class, 'userLogout'])->name('logout');

});

Route::get('language/{locale?}', function ($locale = null) {
    if (isset($locale) && in_array($locale, config('app.available_locales'))) {
        
        App::setLocale($locale);
        Session::put('locale', $locale);

        URL::defaults(['locale' => $locale]);

        Artisan::call('optimize:clear');
        return true;
    }
    
});

app/Models/Admin.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Admin extends Authenticatable
{
    use Notifiable, HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'status'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
        'status'
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Admin/AdminController.php
<?php

namespace App\Http\Controllers\Admin;

use App\DataTables\UsersListDataTable;
use App\Http\Controllers\Controller;
use App\Http\Requests\Admin\StoreOrUpdateUserDetailsRequest;
use App\Models\User;
use App\Repositories\AdminRepository;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class AdminController extends Controller
{
    private $adminRepository;

    public function __construct(AdminRepository $adminRepository)
    {
        $this->adminRepository = $adminRepository;
        $this->middleware('auth_admin');
    }

    /*
     * After logging as admin the dashboard for admin
     * @return \Illuminate\Contracts\Support\Referable
     * */
    public function adminDashboard()
    {
        return view('admin.dashboard');
    }

    public function index(UsersListDataTable $dataTable)
    {
        return $dataTable->render('admin.users-list');
    }

    /**
     * creating new user form loading
     */

    public function getNewUserForm()
    {
        return view('admin.create-user');
    }

    public function storeUserDetails(StoreOrUpdateUserDetailsRequest $request)
    {
        try {

            $user = $this->adminRepository->createNew($request->all());

            return response()->json([
                'success' => true,
                'message' => __('form-elements.user_created_successfully'),
                'data' => $user,
                'code' => 200
            ], 200);
        } catch(Exception $e) {
            dd($e);
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());
        }
    }

    public function getUpdateUserForm($id)
    {
        $user = User::find($id);
        if($user) {

            return View('admin.edit-user', compact('user'));
        }
        
        return back()->with('commonError', __('form-elements.user_data_not_found'));
    }

    public function updateUserDetails (StoreOrUpdateUserDetailsRequest $request)
    {
        try {

            $user = $this->adminRepository->updateUserInfo($request->user_id, $request->all());

            return response()->json([
                'success' => true,
                'message' => __('form-elements.user_details_updated_successfully'),
                'data' => $user,
                'code' => 200
            ], 200);
        } catch(Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());
        }
    }

    public function deleteUser($id)
    {
        try {

            $user = User::find($id)->delete();

            return response()->json([
                'success' => true,
                'message' => __('form-elements.user_deleted_successfully'),
                'data' => $user,
                'code' => 200
            ], 200);
        } catch(Exception $e) {
            return response()->json([
                'success' => false,
                'message' => $e->getMessage(),
                'errors' => [],
                'code' => $e->getCode()
            ], $e->getCode());
        }
    }
    /**
     * Logout function
     *
     * @return void
     */
    public function adminLogout()
    {
        Auth::guard('admin')->logout();
        return redirect()->route('login');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/User/UserController.php
<?php

namespace App\Http\Controllers\User;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth_user');
    }

    /*
     * After logging as user the dashboard for user
     * @return \Illuminate\Contracts\Support\Referable
     * */
    public function userDashboard()
    {
        return view('user.dashboard');
    }

    /**
     * Logout function
     *
     * @return void
     */
    public function userLogout()
    {
        Auth::guard('user')->logout();
        return redirect()->route('login');
    }
}

resources/views/admin/create-user.blade.php
@extends('layouts.app')
@section('pageTitle','Create User')
@push('css')
<style>

    .wrap-login100 {
        width: 1203px !important;
        height: 770px;

        padding: 24px 130px 33px 95px !important;
    }

    .table-body {
        width: 1203px !important;
    }

    #user-details-datatable {
        width: 100% !important;
    }

    .bg-gradient-success {
        color: green !important;
    }

    .bg-gradient-secondary {
        color: red !important;
    }

    .form-body {
        box-sizing: border-box;
        width: 100%;
        min-height: 88%;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        /* align-items: center; */
        /* padding: 15px; */
        background: #e9ecef;
        margin-left: 25%;
        
    }

    form {
        width: 100%;
        padding: 28px 8px 8px 61px;
    }

    .common-success {
        text-align: right;
        margin-bottom:5px;
    }

    .col-md-12 {
        margin-top: 8px !important;
    }

    label {
        margin-bottom: 0 !important;
    }
    .create-btn {
        margin-top: 50px;
        background-color: #007bff;
        border-color: #007bff;
    }

    input[type="radio"] {
        margin-left: 50px !important ;
        margin-right: 5px !important ;
    }

    .invalid-feedback {
        margin-left: 25px;
    }
</style>

@endpush
@section('content')
    <div class="wrap-login100">
            <div class="relative items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0 table-body">
                    <!-- <span class="app-name">Users List</span> -->
                    <div class="row" style="margin-bottom:5px;">
                        <div class="col-md-6" style="text-align: left;">
                            <a href="{{ route('admin.dashboard') }}" class="btn btn-info"><i class="fa fa-home" aria-hidden="true"></i> {{ __('form-elements.dashboard') }}</a>
                        </div>
                        <div class="col-md-6" style="text-align: right;">
                            <a href="{{ route('admin.users-list') }}" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('form-elements.back_to_list') }}</a>
                        </div>
                    </div>
                    <div class="form-body col-6">
                        <form class="" id="create-or-update-user" data-url="{{ route('admin.store-user') }}">
                        {{ csrf_field() }}
                            <div class="row" style="width: 100% !important;">
                                    <div class="col-md-12 data-field">
                                        <label class="form-label" for="">{{ __('form-elements.user_name')}}: </label>
                                        <input type="text" class="form-control" name="name" placeholder="{{ __('form-elements.full_name') }}" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode == 32)">
                                        
                                    </div>
                                    
                                    <div class="col-md-12 data-field">
                                        <label class="form-label" for="">{{ __('form-elements.user_email') }}: </label>
                                        <input type="text" class="form-control" name="email" placeholder="{{ __('form-elements.placeholder_email') }}">
                                    </div>

                                    <div class="col-md-12 data-field">
                                        <label class="form-label">{{ __('form-elements.user_status') }}: </label>
                                        <div class="input-group input-group-outline">
                                            <input type="radio" class="radio" id="active" name="status" value="1" checked><label for="active">{{ __('form-elements.active_user') }}</label>
                                            <input type="radio" class="radio" id="inactive" name="status" value="0"><label for="inactive">{{ __('form-elements.inactive_user') }}</label>

                                        </div>
                                    </div>

                                    <div class="text-center col-12">
                                        <button type="submit" class="btn btn-info create-btn">{{ __('form-elements.create_user') }}</button>
                                    </div>
                                </div>

                        </form>
                    </div>
            </div>

    </div>
@endsection

@push('js')

<script>
    var field_required = "{{ __('extra-validation.field_required')}}",
        invalid_email = "{{ __('extra-validation.valid_email')}}";
</script>

<script src="{{ asset('js/admin/create-or-update-user.js')}}"></script>



@endpush

resources/views/admin/dashboard.blade.php
@extends('layouts.app')
@section('pageTitle','Dashboard')
@push('css')
<style>

.wrap-login100 {
    width: 269px !important;
    padding: 50px 50px 50px 75px!important;
    color: #d722d7;
    font-weight: 700;
}

.col-md-123 {
    margin-top: -500px !important;
    margin-right: 5px !important;
}

</style>

@endpush
@section('content')
    <div class="col-md-123">
        <a href="{{ route('admin.users-list') }}">
            <div class="wrap-login100">
                {{ __('form-elements.user_list')}}

            </div>
        </a>
    </div>                  
    <div class="col-md-123">
        <a href="{{ route('admin.create-user') }}">
            <div class="wrap-login100">
                {{ __('form-elements.create_user_form')}}

            </div>
        </a>
    </div>
    <div class="col-md-123">
        <a href="{{ route('admin.logout') }}">
            <div class="wrap-login100">
                {{ __('form-elements.logout')}}

            </div>
        </a>
    </div>

@endsection

resources/views/admin/edit-user.blade.php
@extends('layouts.app')
@section('pageTitle','Edit User')
@push('css')

<style>

    .wrap-login100 {
        width: 1203px !important;
        height: 770px;

        padding: 24px 130px 33px 95px !important;
    }

    .table-body {
        width: 1203px !important;
    }

    #user-details-datatable {
        width: 100% !important;
    }

    .bg-gradient-success {
        color: green !important;
    }

    .bg-gradient-secondary {
        color: red !important;
    }

    .form-body {
        box-sizing: border-box;
        width: 100%;
        min-height: 88%;
        display: flex;
        flex-wrap: wrap;
        justify-content: center;
        /* align-items: center; */
        /* padding: 15px; */
        background: #e9ecef;
        margin-left: 25%;
        
    }

    form {
        width: 100%;
        padding: 28px 8px 8px 61px;
    }

    .common-success {
        text-align: right;
        margin-bottom:5px;
    }

    .col-md-12 {
        margin-top: 8px !important;
    }

    label {
        margin-bottom: 0 !important;
    }
    .create-btn {
        margin-top: 50px;
        background-color: #007bff;
        border-color: #007bff;
    }

    input[type="radio"] {
        margin-left: 50px !important ;
        margin-right: 5px !important ;
    }

    .invalid-feedback {
        margin-left: 25px;
    }
</style>

@endpush
@section('content')
    <div class="wrap-login100">
            <div class="relative items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0 table-body">
                    <!-- <span class="app-name">Users List</span> -->
                    <div class="row" style="margin-bottom:5px;">
                        <div class="col-md-6" style="text-align: left;">
                            <a href="{{ route('admin.dashboard') }}" class="btn btn-info"><i class="fa fa-home" aria-hidden="true"></i> {{ __('form-elements.dashboard') }}</a>
                        </div>
                        <div class="col-md-6" style="text-align: right;">
                            <a href="{{ route('admin.users-list') }}" class="btn btn-info"><i class="fa fa-arrow-left" aria-hidden="true"></i> {{ __('form-elements.back_to_list') }}</a>
                        </div>
                    </div>
                    <div class="form-body col-6">
                        <form class="" id="create-or-update-user" data-url="{{ route('admin.update-user') }}">
                        {{ csrf_field() }}
                            <div class="row" style="width: 100% !important;">
                                    <div class="col-md-12 data-field">
                                        <label class="form-label" for="">{{ __('form-elements.user_name')}}: </label>
                                        <input type="text" class="form-control" name="name" value="{{ $user->name }}" placeholder="{{ __('form-elements.full_name') }}" onkeypress="return (event.charCode > 64 && event.charCode < 91) || (event.charCode > 96 && event.charCode < 123) || (event.charCode == 32)">
                                        
                                    </div>
                                    
                                    <div class="col-md-12 data-field">
                                        <label class="form-label" for="">{{ __('form-elements.user_email') }}: </label>
                                        <input type="text" class="form-control" value="{{ $user->email }}" name="email" placeholder="{{ __('form-elements.placeholder_email') }}">
                                    </div>

                                    <div class="col-md-12 data-field">
                                        <label class="form-label">{{ __('form-elements.user_status') }}: </label>
                                        <div class="input-group input-group-outline">
                                            <input type="radio" class="radio" id="active" name="status" value="1" {{($user->status == 1) ? 'checked' : ''}}><label for="active">{{ __('form-elements.active_user') }}</label>
                                            <input type="radio" class="radio" id="inactive" name="status" value="0" {{($user->status == 0) ? 'checked' : ''}}><label for="inactive">{{ __('form-elements.inactive_user') }}</label>

                                        </div>
                                    </div>

                                    <div class="col-md-12 data-field">
                                        <label class="form-label">{{ __('form-elements.reset_password') }}: </label>
                                        <div class="input-group input-group-outline">
                                            <input type="radio" class="radio" id="yes" name="reset_password" value="1"><label for="yes">{{ __('form-elements.yes') }}</label>
                                            <input type="radio" class="radio" id="no" name="reset_password" value="0" checked><label for="no">{{ __('form-elements.no') }}</label>

                                        </div>
                                    </div>
                                    <input type="hidden" name="user_id" value="{{ $user->id }}"/>
                                    <div class="text-center col-12">
                                        <button type="submit" class="btn btn-info create-btn">{{ __('form-elements.update_user') }}</button>
                                    </div>
                                </div>

                        </form>
                    </div>
            </div>

    </div>
@endsection

@push('js')
<script>
    var field_required = "{{ __('extra-validation.field_required')}}",
        invalid_email = "{{ __('extra-validation.valid_email')}}";
</script>

<script src="{{ asset('js/admin/create-or-update-user.js')}}"></script>



@endpush

resources/views/admin/users-list.blade.php
@extends('layouts.app')
@section('pageTitle','User List')
@push('css')
<style>

    .wrap-login100 {
        width: 1203px !important;
        height: 770px;
        padding: 24px 130px 33px 95px !important
    }

    .table-body {
        width: 1203px !important;
    }

    #user-details-datatable {
        width: 100% !important;
    }

    .bg-gradient-success {
        color: green !important;
    }

    .bg-gradient-secondary {
        color: red !important;
    }
</style>

@endpush
@section('content')
    <div class="wrap-login100">
            <div class="relative items-top justify-center min-h-screen bg-gray-100 dark:bg-gray-900 sm:items-center py-4 sm:pt-0 table-body">
                    <!-- <span class="app-name">Users List</span> -->
                    <div class="row" style="margin-bottom:5px;">
                        <div class="col-md-6" style="text-align: left;">
                            <a href="{{ route('admin.dashboard') }}" class="btn btn-info"><i class="fa fa-home" aria-hidden="true"></i> {{ __('form-elements.dashboard') }}</a>
                        </div>
                        <div class="col-md-6" style="text-align: right;">
                            <a href="{{ route('admin.create-user') }}" class="btn btn-info"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('form-elements.create_user_form') }}</a>
                        </div>
                    </div>

                    <div class="card-header">
                        <form class="" id="filter-form">
                            <!-- <label class="mr-sm-2 form-label" for="admin-user-search">Search by:</label>
                            <input type="text" class="form-control search mb-2 mr-sm-2 mb-sm-0" id="filter-search"
                                placeholder="Search ..."> -->

                            <div class="row" style="width: 100% !important;">
                                <div class="col-md-4">
                                    <label class="form-label" for="">{{ __('form-elements.search_by') }}: </label>
                                    <input type="text" class="form-control search mb-2 mr-sm-2 mb-sm-0" id="filter-search" placeholder="{{ __('form-elements.search') }} ...">
                                </div>
                                
                                <div class="col-md-4">
                                    <label class="form-label" for="admin-user-search">{{ __('form-elements.user_status') }} </label>
                                    <select class="custom-select mb-2 mr-sm-2 mb-sm-0" id="filter-status">
                                        <option value="">{{ __('form-elements.all_status') }}</option>

                                        <option value="1">{{ __('form-elements.active_user') }}</option>
                                        <option value="0">{{ __('form-elements.inactive_user') }}</option>

                                    </select>
                                </div>
                            </div>
                        </form>
                    </div>
                    <!-- DataTable init -->
                    <div class="table-responsive">
                        
                        @component('components.datatable',compact('dataTable')) @endcomponent
                    </div>
            </div>

    </div>
@endsection

@push('js')
<script>
    const userDeleteURL = "{{ route('admin.delete-user') }}"; 
</script>
<script src="{{ asset('js/admin/user-list.js')}}"></script>

@endpush

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
    @include('layouts.header')
    <body>
        <div class="limiter">
            <div class="container-login100">
                <div class="col-12 trans-div">
                    @php
                        $available_locales  = config('app.available_locales');
                        $current_locale     = session()->get('locale') ?: app()->getLocale();
                    @endphp
                    <select class="form-select form-select-sm" id="trans-lang" aria-label=".form-select-sm example">
                        @foreach($available_locales as $locale_name => $available_locale)
                            @php $selected = ''; @endphp
                            @if($available_locale === $current_locale)
                                @php $selected = 'selected'; @endphp
                            @endif
                                <option value="{{ $available_locale }}" {{$selected}}>{{ $locale_name }}</option>
                        @endforeach
                    </select>
                    
                </div>

                <div class="col-md-12">
                
                    @if (session('commonError'))
                        <div class="alert alert-warning alert-dismissible text-white" role="alert">
                            <span class="text-sm">{{ session('commonError') }}</span>
                        </div>
                    @endif
                    <div class="alert alert-danger alert-dismissible text-white" role="alert" style="display: none;">
                        <span class="text-sm">
                            A simple danger alert with an example link. Give it a click if you like.
                        </span>
                    </div>
                    <div class="alert alert-success alert-dismissible text-white" role="alert" style="display: none;">
                        <span class="text-sm">
                            A simple danger alert with an example link. Give it a click if you like.
                        </span>
                    </div>
                </div>
                @yield('content')
            </div>
        </div>
        
    </body>
    @include('layouts.footer-js')
</html>

resources/views/layouts/footer-js.blade.php
<script src="{{ asset('/vendor/jquery/jquery-3.2.1.min.js') }}"></script>

<script src="{{ asset('/vendor/bootstrap/js/popper.js') }}"></script>
<script src="{{ asset('/vendor/bootstrap/js/bootstrap.min.js') }}"></script>

<script src="{{ asset('/vendor/select2/select2.min.js') }}"></script>

<script src="{{ asset('/vendor/tilt/tilt.jquery.min.js') }}"></script>
<script>
		$('.js-tilt').tilt({
			scale: 1.1
		})
	</script>

<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

<script src="{{ asset('/js/main.js') }}"></script>
<script defer src="https://static.cloudflareinsights.com/beacon.min.js/vaafb692b2aea4879b33c060e79fe94621666317369993" integrity="sha512-0ahDYl866UMhKuYcW078ScMalXqtFJggm7TmlUtp0UlD4eQk0Ixfnm5ykXKvGJNFjLMoortdseTfsRT8oCfgGA==" data-cf-beacon='{"rayId":"79a45aa50dbf85bd","token":"cd0b4b3a733644fc843ef0b185f98241","version":"2023.2.0","si":100}' crossorigin="anonymous"></script>
<script src="{{ asset('js/sweetalert2@11.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.8/js/select2.min.js" defer></script>
<!-- Font Awesome Icons -->
<script src="https://kit.fontawesome.com/42d5adcbca.js" crossorigin="anonymous"></script>
<script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
<script>
  var something_went_wrong  = "{{__('form-elements.something_went_wrong')}}",
      user_not_deleted      = "{{__('form-elements.user_not_deleted')}}",
      delete_confirmation   = "{{__('form-elements.delete_confirmation')}}";

</script>
<script src="{{ asset('js/admin/trans-language.js')}}"></script>
@stack('js')

resources/views/layouts/header.blade.php
<head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="icon" type="image/png" href="{{ asset('/images/icons/favicon.ico') }}" />

        <link rel="stylesheet" type="text/css" href="{{ asset('/vendor/bootstrap/css/bootstrap.min.css') }}">
        
        <meta name="csrf-token" content="{{ csrf_token() }}">
        <title>{{ config('app.name') }} | @yield('pageTitle')</title>

        <!-- <link rel="stylesheet" type="text/css" href="{{ asset('/fonts/font-awesome-4.7.0/css/font-awesome.min.css') }}"> -->
        <link rel="stylesheet" href="{{ asset('css/sweetalert2.css') }}">
        <!--     Fonts and icons     -->
        <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700,900|Roboto+Slab:400,700" />

        <link rel="stylesheet" type="text/css" href="{{ asset('/vendor/animate/animate.css') }}">

        <link rel="stylesheet" type="text/css" href="{{ asset('/vendor/select2/select2.min.css') }}">

        <link rel="stylesheet" type="text/css" href="{{ asset('/css/util.css') }}">
        <link rel="stylesheet" type="text/css" href="{{ asset('/css/main.css') }}">

        <meta name="robots" content="noindex, follow">
        <style>
            .alert {
                width: 550px;
                float: right;
            }
            .alert-success {
                background-color: #155724 !important;
                border-color: #155724 !important;
            }
            .alert-danger {
                background-color: #721c24 !important;
                border-color: #721c24 !important;
            }

            .alert-warning {
                background-color: #dbbd5c !important;
                border-color: #dbbd5c !important;
            }

            
        </style>
        
        @stack('css')

  </head>

resources/views/user/dashboard.blade.php
@extends('layouts.app')
@section('pageTitle','Dashboard')
@push('css')
<style>

.user-dashboard {
    margin-top: -800px !important;
    margin-right: 5px !important;
    font-weight: 700;
    font-size: 70px;
}
a {
    width: 249px !important;
    color: #e90f0f !important;
    font-size: 50px;
    font-weight: 400;


}
</style>

@endpush
@section('content')
    <div class="user-dashboard">
    {{__('form-elements.welcome_user')}}
    </div>    
    <a href="{{ route('user.logout') }}">
        {{ __('form-elements.logout')}}
    </a>
@endsection